@CopylaneSalesInventory.API_HostAddress = http://localhost:5127

GET {{CopylaneSalesInventory.API_HostAddress}}/weatherforecast/
Accept: application/json

### Create a New Product
POST {{CopylaneSalesInventory.API_HostAddress}}/api/product
Content-Type: application/json
{
  "sku": "LAPTOP-001",
  "barcode": "laptop-001",
  "name": "Gaming Laptop",
  "description": "Gaming laptop",
  "unitprice": 45000,
  "reorderlevel": 5,
  "createdbyid": 1
}

### Update Product
PUT {{CopylaneSalesInventory.API_HostAddress}}/api/product/1
Content-Type: application/json
{
  "id": 1,
  "sku": "LAPTOP-001",
  "barcode": "laptop-001",
  "name": "Gaming Laptop",
  "description": "Gaming laptop",
  "unitprice": 55000,
  "reorderlevel": 10,
  "modifiedbyid": 2
}

### Change Product Status
PATCH {{CopylaneSalesInventory.API_HostAddress}}/api/product/1/status
Content-Type: application/json
{
  "id": 1,
  "isactive": false,
  "modifiedbyid": 2
}

### Get Products
GET {{CopylaneSalesInventory.API_HostAddress}}/api/product
